### ISSUE TITLE
Resumable upload example

### ISSUE THREAD

**Issue by lecndav** [eventials/go-tus#27]
Hi,

is there a working example with resumable upload?

I want to loop over a directory and upload all files (new files are dynamically copied in the directory). If the connection to the server gets interrupted, I want that the tus client continues uploading once the connection is back. I guess, that is what the `Resume` flag in the config supports.

Thanks in advance,
David

**Comment by silviogreuel** [comment]
The README.md file has one https://github.com/eventials/go-tus#example

**Comment by lecndav** [comment]
Yeah, but does it support resumable upload?

Additionally, how do I know, if the upload has finished? Is there a notification or do I have to loop over `upload.Finished()` and wait for it?

**Comment by silviogreuel** [comment]
Ah, ok, just browsing some files: 

**Resumable**

Pass a custom config:
https://github.com/eventials/go-tus/blob/master/client.go#L27 

Set a store on config:
https://github.com/eventials/go-tus/blob/master/config.go#L26 

Then, instead of `CreateUpload` use `CreateOrResumeUpload`
https://github.com/eventials/go-tus/blob/master/client.go#L157 

**Pogress**
Just add a listener here, you will receive an update on every chunk uploaded
https://github.com/eventials/go-tus/blob/master/uploader.go#L18


And yep, really hard without a example and lack of some tests...

**Comment by skrater** [comment]
@lecndav Yes, the lib support resume upload, just use `CreateOrResumeUpload`. 

Check upload completed depends on your application you can just wait for `uploader.Upload()` returns a nil error.

**Comment by ajeecai** [comment]
Although this issue has been closed,  just want to post one example from me https://gist.github.com/ajeecai/cf2a7742bdf746efde543f34e0e4ac61
